DROP TABLE IF EXISTS covid_deaths;
DROP TABLE IF EXISTS covid_vaccinations;
DROP TABLE IF EXISTS covid_deaths_raw;
DROP TABLE IF EXISTS covid_vaccinations_raw;

CREATE TABLE covid_deaths_raw (
    iso_code TEXT,
    continent TEXT,
    location TEXT,
    date TEXT,
    total_cases TEXT,
    new_cases TEXT,
    new_cases_smoothed TEXT,
    total_deaths TEXT,
    new_deaths TEXT,
    new_deaths_smoothed TEXT,
    total_cases_per_million TEXT,
    new_cases_per_million TEXT,
    new_cases_smoothed_per_million TEXT,
    total_deaths_per_million TEXT,
    new_deaths_per_million TEXT,
    new_deaths_smoothed_per_million TEXT,
    reproduction_rate TEXT,
    icu_patients TEXT,
    icu_patients_per_million TEXT,
    hosp_patients TEXT,
    hosp_patients_per_million TEXT,
    weekly_icu_admissions TEXT,
    weekly_icu_admissions_per_million TEXT,
    weekly_hosp_admissions TEXT,
    weekly_hosp_admissions_per_million TEXT,
    new_tests TEXT,
    total_tests TEXT,
    total_tests_per_thousand TEXT,
    new_tests_per_thousand TEXT,
    new_tests_smoothed TEXT,
    new_tests_smoothed_per_thousand TEXT,
    positive_rate TEXT,
    tests_per_case TEXT,
    tests_units TEXT,
    total_vaccinations TEXT,
    people_vaccinated TEXT,
    people_fully_vaccinated TEXT,
    new_vaccinations TEXT,
    new_vaccinations_smoothed TEXT,
    total_vaccinations_per_hundred TEXT,
    people_vaccinated_per_hundred TEXT,
    people_fully_vaccinated_per_hundred TEXT,
    new_vaccinations_smoothed_per_million TEXT,
    stringency_index TEXT,
    population TEXT,
    population_density TEXT,
    median_age TEXT,
    aged_65_older TEXT,
    aged_70_older TEXT,
    gdp_per_capita TEXT,
    extreme_poverty TEXT,
    cardiovasc_death_rate TEXT,
    diabetes_prevalence TEXT,
    female_smokers TEXT,
    male_smokers TEXT,
    handwashing_facilities TEXT,
    hospital_beds_per_thousand TEXT,
    life_expectancy TEXT,
    human_development_index TEXT
);

CREATE TABLE covid_vaccinations_raw (
    iso_code TEXT,
    continent TEXT,
    location TEXT,
    date TEXT,
    new_tests TEXT,
    total_tests TEXT,
    total_tests_per_thousand TEXT,
    new_tests_per_thousand TEXT,
    new_tests_smoothed TEXT,
    new_tests_smoothed_per_thousand TEXT,
    positive_rate TEXT,
    tests_per_case TEXT,
    tests_units TEXT,
    total_vaccinations TEXT,
    people_vaccinated TEXT,
    people_fully_vaccinated TEXT,
    new_vaccinations TEXT,
    new_vaccinations_smoothed TEXT,
    total_vaccinations_per_hundred TEXT,
    people_vaccinated_per_hundred TEXT,
    people_fully_vaccinated_per_hundred TEXT,
    new_vaccinations_smoothed_per_million TEXT,
    stringency_index TEXT,
    population_density TEXT,
    median_age TEXT,
    aged_65_older TEXT,
    aged_70_older TEXT,
    gdp_per_capita TEXT,
    extreme_poverty TEXT,
    cardiovasc_death_rate TEXT,
    diabetes_prevalence TEXT,
    female_smokers TEXT,
    male_smokers TEXT,
    handwashing_facilities TEXT,
    hospital_beds_per_thousand TEXT,
    life_expectancy TEXT,
    human_development_index TEXT
);

COPY covid_deaths_raw
FROM 'D:/Data Analysis project/SQL/Project 2/CovidDeaths.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ';', ENCODING 'UTF8');

COPY covid_vaccinations_raw
FROM 'D:/Data Analysis project/SQL/Project 2/CovidVaccinations.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ';', ENCODING 'UTF8');

CREATE TABLE covid_deaths AS
SELECT
    iso_code,
    continent,
    location,
    to_date(TRIM(date), 'DD.MM.YYYY') AS date,
    NULLIF(REPLACE(TRIM(total_cases), ',', '.'), '')::numeric AS total_cases,
    NULLIF(REPLACE(TRIM(new_cases), ',', '.'), '')::numeric AS new_cases,
    NULLIF(REPLACE(TRIM(new_cases_smoothed), ',', '.'), '')::numeric AS new_cases_smoothed,
    NULLIF(REPLACE(TRIM(total_deaths), ',', '.'), '')::numeric AS total_deaths,
    NULLIF(REPLACE(TRIM(new_deaths), ',', '.'), '')::numeric AS new_deaths,
    NULLIF(REPLACE(TRIM(new_deaths_smoothed), ',', '.'), '')::numeric AS new_deaths_smoothed,
    NULLIF(REPLACE(TRIM(total_cases_per_million), ',', '.'), '')::numeric AS total_cases_per_million,
    NULLIF(REPLACE(TRIM(new_cases_per_million), ',', '.'), '')::numeric AS new_cases_per_million,
    NULLIF(REPLACE(TRIM(new_cases_smoothed_per_million), ',', '.'), '')::numeric AS new_cases_smoothed_per_million,
    NULLIF(REPLACE(TRIM(total_deaths_per_million), ',', '.'), '')::numeric AS total_deaths_per_million,
    NULLIF(REPLACE(TRIM(new_deaths_per_million), ',', '.'), '')::numeric AS new_deaths_per_million,
    NULLIF(REPLACE(TRIM(new_deaths_smoothed_per_million), ',', '.'), '')::numeric AS new_deaths_smoothed_per_million,
    NULLIF(REPLACE(TRIM(reproduction_rate), ',', '.'), '')::numeric AS reproduction_rate,
    NULLIF(REPLACE(TRIM(icu_patients), ',', '.'), '')::numeric AS icu_patients,
    NULLIF(REPLACE(TRIM(icu_patients_per_million), ',', '.'), '')::numeric AS icu_patients_per_million,
    NULLIF(REPLACE(TRIM(hosp_patients), ',', '.'), '')::numeric AS hosp_patients,
    NULLIF(REPLACE(TRIM(hosp_patients_per_million), ',', '.'), '')::numeric AS hosp_patients_per_million,
    NULLIF(REPLACE(TRIM(weekly_icu_admissions), ',', '.'), '')::numeric AS weekly_icu_admissions,
    NULLIF(REPLACE(TRIM(weekly_icu_admissions_per_million), ',', '.'), '')::numeric AS weekly_icu_admissions_per_million,
    NULLIF(REPLACE(TRIM(weekly_hosp_admissions), ',', '.'), '')::numeric AS weekly_hosp_admissions,
    NULLIF(REPLACE(TRIM(weekly_hosp_admissions_per_million), ',', '.'), '')::numeric AS weekly_hosp_admissions_per_million,
    NULLIF(REPLACE(TRIM(new_tests), ',', '.'), '')::numeric AS new_tests,
    NULLIF(REPLACE(TRIM(total_tests), ',', '.'), '')::numeric AS total_tests,
    NULLIF(REPLACE(TRIM(total_tests_per_thousand), ',', '.'), '')::numeric AS total_tests_per_thousand,
    NULLIF(REPLACE(TRIM(new_tests_per_thousand), ',', '.'), '')::numeric AS new_tests_per_thousand,
    NULLIF(REPLACE(TRIM(new_tests_smoothed), ',', '.'), '')::numeric AS new_tests_smoothed,
    NULLIF(REPLACE(TRIM(new_tests_smoothed_per_thousand), ',', '.'), '')::numeric AS new_tests_smoothed_per_thousand,
    NULLIF(REPLACE(TRIM(positive_rate), ',', '.'), '')::numeric AS positive_rate,
    NULLIF(REPLACE(TRIM(tests_per_case), ',', '.'), '')::numeric AS tests_per_case,
    tests_units,
    NULLIF(REPLACE(TRIM(total_vaccinations), ',', '.'), '')::numeric AS total_vaccinations,
    NULLIF(REPLACE(TRIM(people_vaccinated), ',', '.'), '')::numeric AS people_vaccinated,
    NULLIF(REPLACE(TRIM(people_fully_vaccinated), ',', '.'), '')::numeric AS people_fully_vaccinated,
    NULLIF(REPLACE(TRIM(new_vaccinations), ',', '.'), '')::numeric AS new_vaccinations,
    NULLIF(REPLACE(TRIM(new_vaccinations_smoothed), ',', '.'), '')::numeric AS new_vaccinations_smoothed,
    NULLIF(REPLACE(TRIM(total_vaccinations_per_hundred), ',', '.'), '')::numeric AS total_vaccinations_per_hundred,
    NULLIF(REPLACE(TRIM(people_vaccinated_per_hundred), ',', '.'), '')::numeric AS people_vaccinated_per_hundred,
    NULLIF(REPLACE(TRIM(people_fully_vaccinated_per_hundred), ',', '.'), '')::numeric AS people_fully_vaccinated_per_hundred,
    NULLIF(REPLACE(TRIM(new_vaccinations_smoothed_per_million), ',', '.'), '')::numeric AS new_vaccinations_smoothed_per_million,
    NULLIF(REPLACE(TRIM(stringency_index), ',', '.'), '')::numeric AS stringency_index,
    NULLIF(REPLACE(TRIM(population), ',', '.'), '')::numeric AS population,
    NULLIF(REPLACE(TRIM(population_density), ',', '.'), '')::numeric AS population_density,
    NULLIF(REPLACE(TRIM(median_age), ',', '.'), '')::numeric AS median_age,
    NULLIF(REPLACE(TRIM(aged_65_older), ',', '.'), '')::numeric AS aged_65_older,
    NULLIF(REPLACE(TRIM(aged_70_older), ',', '.'), '')::numeric AS aged_70_older,
    NULLIF(REPLACE(TRIM(gdp_per_capita), ',', '.'), '')::numeric AS gdp_per_capita,
    NULLIF(REPLACE(TRIM(extreme_poverty), ',', '.'), '')::numeric AS extreme_poverty,
    NULLIF(REPLACE(TRIM(cardiovasc_death_rate), ',', '.'), '')::numeric AS cardiovasc_death_rate,
    NULLIF(REPLACE(TRIM(diabetes_prevalence), ',', '.'), '')::numeric AS diabetes_prevalence,
    NULLIF(REPLACE(TRIM(female_smokers), ',', '.'), '')::numeric AS female_smokers,
    NULLIF(REPLACE(TRIM(male_smokers), ',', '.'), '')::numeric AS male_smokers,
    NULLIF(REPLACE(TRIM(handwashing_facilities), ',', '.'), '')::numeric AS handwashing_facilities,
    NULLIF(REPLACE(TRIM(hospital_beds_per_thousand), ',', '.'), '')::numeric AS hospital_beds_per_thousand,
    NULLIF(REPLACE(TRIM(life_expectancy), ',', '.'), '')::numeric AS life_expectancy,
    NULLIF(REPLACE(TRIM(human_development_index), ',', '.'), '')::numeric AS human_development_index
FROM covid_deaths_raw;

CREATE TABLE covid_vaccinations AS
SELECT
    iso_code,
    continent,
    location,
    to_date(TRIM(date), 'DD.MM.YYYY') AS date,
    NULLIF(REPLACE(TRIM(new_tests), ',', '.'), '')::numeric AS new_tests,
    NULLIF(REPLACE(TRIM(total_tests), ',', '.'), '')::numeric AS total_tests,
    NULLIF(REPLACE(TRIM(total_tests_per_thousand), ',', '.'), '')::numeric AS total_tests_per_thousand,
    NULLIF(REPLACE(TRIM(new_tests_per_thousand), ',', '.'), '')::numeric AS new_tests_per_thousand,
    NULLIF(REPLACE(TRIM(new_tests_smoothed), ',', '.'), '')::numeric AS new_tests_smoothed,
    NULLIF(REPLACE(TRIM(new_tests_smoothed_per_thousand), ',', '.'), '')::numeric AS new_tests_smoothed_per_thousand,
    NULLIF(REPLACE(TRIM(positive_rate), ',', '.'), '')::numeric AS positive_rate,
    NULLIF(REPLACE(TRIM(tests_per_case), ',', '.'), '')::numeric AS tests_per_case,
    tests_units,
    NULLIF(REPLACE(TRIM(total_vaccinations), ',', '.'), '')::numeric AS total_vaccinations,
    NULLIF(REPLACE(TRIM(people_vaccinated), ',', '.'), '')::numeric AS people_vaccinated,
    NULLIF(REPLACE(TRIM(people_fully_vaccinated), ',', '.'), '')::numeric AS people_fully_vaccinated,
    NULLIF(REPLACE(TRIM(new_vaccinations), ',', '.'), '')::numeric AS new_vaccinations,
    NULLIF(REPLACE(TRIM(new_vaccinations_smoothed), ',', '.'), '')::numeric AS new_vaccinations_smoothed,
    NULLIF(REPLACE(TRIM(total_vaccinations_per_hundred), ',', '.'), '')::numeric AS total_vaccinations_per_hundred,
    NULLIF(REPLACE(TRIM(people_vaccinated_per_hundred), ',', '.'), '')::numeric AS people_vaccinated_per_hundred,
    NULLIF(REPLACE(TRIM(people_fully_vaccinated_per_hundred), ',', '.'), '')::numeric AS people_fully_vaccinated_per_hundred,
    NULLIF(REPLACE(TRIM(new_vaccinations_smoothed_per_million), ',', '.'), '')::numeric AS new_vaccinations_smoothed_per_million,
    NULLIF(REPLACE(TRIM(stringency_index), ',', '.'), '')::numeric AS stringency_index,
    NULLIF(REPLACE(TRIM(population_density), ',', '.'), '')::numeric AS population_density,
    NULLIF(REPLACE(TRIM(median_age), ',', '.'), '')::numeric AS median_age,
    NULLIF(REPLACE(TRIM(aged_65_older), ',', '.'), '')::numeric AS aged_65_older,
    NULLIF(REPLACE(TRIM(aged_70_older), ',', '.'), '')::numeric AS aged_70_older,
    NULLIF(REPLACE(TRIM(gdp_per_capita), ',', '.'), '')::numeric AS gdp_per_capita,
    NULLIF(REPLACE(TRIM(extreme_poverty), ',', '.'), '')::numeric AS extreme_poverty,
    NULLIF(REPLACE(TRIM(cardiovasc_death_rate), ',', '.'), '')::numeric AS cardiovasc_death_rate,
    NULLIF(REPLACE(TRIM(diabetes_prevalence), ',', '.'), '')::numeric AS diabetes_prevalence,
    NULLIF(REPLACE(TRIM(female_smokers), ',', '.'), '')::numeric AS female_smokers,
    NULLIF(REPLACE(TRIM(male_smokers), ',', '.'), '')::numeric AS male_smokers,
    NULLIF(REPLACE(TRIM(handwashing_facilities), ',', '.'), '')::numeric AS handwashing_facilities,
    NULLIF(REPLACE(TRIM(hospital_beds_per_thousand), ',', '.'), '')::numeric AS hospital_beds_per_thousand,
    NULLIF(REPLACE(TRIM(life_expectancy), ',', '.'), '')::numeric AS life_expectancy,
    NULLIF(REPLACE(TRIM(human_development_index), ',', '.'), '')::numeric AS human_development_index
FROM covid_vaccinations_raw;

CREATE INDEX idx_covid_deaths_location_date ON covid_deaths(location, date);
CREATE INDEX idx_covid_vaccinations_location_date ON covid_vaccinations(location, date);
